version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
      - ELASTICSEARCH_CLUSTER_NAME=siem
      - ELASTICSEARCH_BIND_ADDRESS=0.0.0.0
      - ELASTICSEARCH_PORT_NUMBER=9200
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata01:/usr/share/elasticsearch
    networks:
      elkstack_bridge:    

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    hostname: kibana
    environment:
      - server.host="0.0.0.0"
      - ELASTICSEARCH_HOSTS=http://172.17.0.1:9200
    ports:
      - "5601:5601"
    volumes:
      - kibana-data:/usr/share/kibana
    networks:
      elkstack_bridge:

    depends_on:
      - elasticsearch

volumes:
  esdata01:
  kibana-data:

networks:
  elkstack_bridge:
    driver: bridge
